In [5]:
import pandas as pd
import math

In [16]:
fb = pd.read_excel("/Users/nellyta/Downloads/jedha ex/Hours Spent on Facebook.xlsx")
print(fb.shape)

(102, 2)

In [17]:
fb.head()

   Customer   Hours spent on Facebook on Mobile
0          1                           4.092475
1          2                           7.233371
2          3                           7.455792
3          4                           7.253503
4          5                           2.249682

In [23]:
mean_fb = fb.mean()

In [24]:
stb_fb = fb.std

In [25]:
t = 1.96

In [20]:
fb.describe()

        Customer   Hours spent on Facebook on Mobile
count  102.000000                         102.000000
mean    51.500000                           4.847316
std     29.588849                           2.978913
min      1.000000                           0.034569
25%     26.250000                           2.300628
50%     51.500000                           4.896723
75%     76.750000                           7.529681
max    102.000000                           9.969544

In [26]:
n_fb = len(fb)

In [ ]:
E = t * stb_fb / sqrt

TypeError: unsupported operand type(s) for *: 'float' and 'method'

In [21]:
gl = pd.read_excel("/Users/nellyta/Downloads/jedha ex/Monthly spending on adwords.xlsx")
print (gl.shape)

(31, 1)